[package]
name = "tueue"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui ="0.29"
color-eyre = "0.6"
strum = { version = "0.27", features = ["derive"] }
tokio = "1.45"
tokio-util = "0.7"
futures = "0.3"
serde = "1"
serde_derive = "1"
crossterm = "0.29"

# [dev-dependencies]
